import type { Business, BusinessRecommendation, Material, Project, Service } from "@/lib/types";

export const services: Service[] = [
  ["woodworking", "Woodworking", "Fabrication for timber furniture, objects and fit-outs.", "Fabrication"],
  ["carpentry", "Carpentry", "Site and workshop carpentry for spatial projects.", "Fabrication"],
  ["cnc-routing", "CNC routing", "Flat-bed routing for wood, plastics and composites.", "Digital fabrication"],
  ["metal-fabrication", "Metal fabrication", "Cutting, bending, welding and assembly for metal work.", "Fabrication"],
  ["cnc-machining", "CNC machining", "Precision milling and turning for metals and plastics.", "Digital fabrication"],
  ["metal-finishing", "Metal finishing", "Anodising, polishing, powder coating and patina work.", "Finishing"],
  ["3d-printing", "3D printing", "Additive manufacturing for prototypes, jigs and small parts.", "Digital fabrication"],
  ["model-making", "Model making", "Architectural, exhibition and product model production.", "Prototyping"],
  ["product-design", "Product design", "Industrial design, prototyping strategy and DFM support.", "Design"],
  ["creative-technology", "Creative technology", "Interactive installations and experience prototyping.", "Technology"],
  ["electronics-prototyping", "Electronics prototyping", "Sensors, lighting, PCB and embedded system prototypes.", "Technology"],
  ["event-fabrication", "Event fabrication", "Temporary structures, pop-ups and activations.", "Spatial"],
  ["installation", "Installation", "Art, retail and exhibition installation support.", "Spatial"],
  ["signage", "Signage", "Wayfinding, dimensional signs and vinyl graphics.", "Print"],
  ["packaging-design", "Packaging design", "Structural and graphic packaging design.", "Design"],
  ["printing", "Printing", "Digital, large-format, risograph and specialty printing.", "Print"],
  ["die-cutting", "Die cutting", "Short-run die cutting, creasing and finishing.", "Print"],
  ["ceramics", "Ceramics", "Clay object prototyping, production and glaze testing.", "Craft"],
  ["mould-making", "Mould making", "Silicone, plaster and production moulds.", "Prototyping"],
  ["kiln-firing", "Kiln firing", "Firing services for clay, glaze and glass work.", "Craft"],
  ["textiles", "Textiles", "Fabric sourcing, sampling and textile construction.", "Soft goods"],
  ["sewing", "Sewing", "Patterning, sewing and soft-goods assembly.", "Soft goods"],
  ["soft-goods-prototyping", "Soft-goods prototyping", "Bags, wearables and fabric object prototypes.", "Soft goods"],
  ["photography", "Photography", "Studio and location photography for products and campaigns.", "Media"],
  ["videography", "Videography", "Production crews for launches, documentation and campaigns.", "Media"],
].map(([slug, name, description, group], index) => ({
  id: `svc_${index + 1}`,
  slug,
  name,
  description,
  group,
}));

export const materials: Material[] = [
  "aluminium",
  "plywood",
  "mild steel",
  "stainless steel",
  "acrylic",
  "brass",
  "ceramic",
  "fabric",
  "paper",
  "cardboard",
  "resin",
  "foam",
  "bamboo",
  "glass",
  "electronics",
  "vinyl",
  "leather",
  "recycled plastic",
].map((name, index) => ({
  id: `mat_${index + 1}`,
  name,
  slug: name.replace(/\s+/g, "-"),
}));

export const businesses: Business[] = [];

export const projects: Project[] = [
  {
    id: "project_aluminium_lamp",
    ownerId: "demo_creative",
    title: "Aluminium table lamp prototype",
    description: "A one-off aluminium lamp with machined hinge details and a warm dimmable LED.",
    intendedOutcome: "Working prototype for photography and investor conversations.",
    projectType: "physical",
    quantity: "1",
    dimensions: "300 x 180 x 420mm",
    materials: ["aluminium", "electronics"],
    knownServices: ["cnc-machining", "electronics-prototyping"],
    prototypeOrProduction: "prototype",
    preferredLocation: "Ubi",
    budgetMin: 2500,
    budgetMax: 7000,
    deadline: "2026-09-15",
    deadlineFlexibility: "Flexible by two weeks",
    status: "draft",
  },
  {
    id: "project_exhibition_wall",
    ownerId: "demo_creative",
    title: "Interactive exhibition wall",
    description: "A travelling exhibition wall with touch sensors, lighting and replaceable graphic panels.",
    intendedOutcome: "Installed experience for a public showcase.",
    projectType: "both",
    materials: ["plywood", "electronics", "vinyl"],
    knownServices: ["creative-technology", "event-fabrication"],
    prototypeOrProduction: "both",
    preferredLocation: "Tai Seng",
    budgetMin: 12000,
    budgetMax: 30000,
    status: "seeking_providers",
  },
  {
    id: "project_ceramic_packaging",
    ownerId: "demo_creative",
    title: "Ceramic gift set and paper sleeve",
    description: "Small ceramic cups with a textured paper sleeve and short-run packaging.",
    intendedOutcome: "Pilot batch for a hospitality client.",
    projectType: "physical",
    materials: ["ceramic", "paper"],
    knownServices: ["ceramics", "packaging-design", "printing"],
    prototypeOrProduction: "production",
    preferredLocation: "Queenstown",
    budgetMin: 3000,
    budgetMax: 9000,
    status: "draft",
  },
  {
    id: "project_softgoods",
    ownerId: "demo_creative",
    title: "Recycled fabric event tote",
    description: "Soft-goods prototype for a durable event tote using recycled fabric.",
    intendedOutcome: "Sample and costing for 300 units.",
    projectType: "physical",
    materials: ["fabric"],
    knownServices: ["sewing", "soft-goods-prototyping"],
    prototypeOrProduction: "both",
    preferredLocation: "Yishun",
    budgetMin: 1500,
    budgetMax: 6000,
    status: "draft",
  },
];

export const businessRecommendations: BusinessRecommendation[] = [];

export function getApprovedRecommendationsForBusiness(businessId: string) {
  return businessRecommendations.filter(
    (recommendation) => recommendation.businessId === businessId && recommendation.status === "approved",
  );
}
