import type { Business, BusinessRecommendation, Material, Project, Service } from "@/lib/types";

export const services: Service[] = [
  ["woodworking", "Woodworking", "Fabrication for timber furniture, objects and fit-outs.", "Fabrication"],
  ["carpentry", "Carpentry", "Site and workshop carpentry for spatial projects.", "Fabrication"],
  ["cnc-routing", "CNC routing", "Flat-bed routing for wood, plastics and composites.", "Digital fabrication"],
  ["metal-fabrication", "Metal fabrication", "Cutting, bending, welding and assembly for metal work.", "Fabrication"],
  ["cnc-machining", "CNC machining", "Precision milling and turning for metals and plastics.", "Digital fabrication"],
  ["metal-finishing", "Metal finishing", "Anodising, polishing, powder coating and patina work.", "Finishing"],
  ["3d-printing", "3D printing", "Additive manufacturing for prototypes, jigs and small parts.", "Digital fabrication"],
  ["model-making", "Model making", "Architectural, exhibition and product model production.", "Prototyping"],
  ["product-design", "Product design", "Industrial design, prototyping strategy and DFM support.", "Design"],
  ["creative-technology", "Creative technology", "Interactive installations and experience prototyping.", "Technology"],
  ["electronics-prototyping", "Electronics prototyping", "Sensors, lighting, PCB and embedded system prototypes.", "Technology"],
  ["event-fabrication", "Event fabrication", "Temporary structures, pop-ups and activations.", "Spatial"],
  ["installation", "Installation", "Art, retail and exhibition installation support.", "Spatial"],
  ["signage", "Signage", "Wayfinding, dimensional signs and vinyl graphics.", "Print"],
  ["packaging-design", "Packaging design", "Structural and graphic packaging design.", "Design"],
  ["printing", "Printing", "Digital, large-format, risograph and specialty printing.", "Print"],
  ["die-cutting", "Die cutting", "Short-run die cutting, creasing and finishing.", "Print"],
  ["ceramics", "Ceramics", "Clay object prototyping, production and glaze testing.", "Craft"],
  ["mould-making", "Mould making", "Silicone, plaster and production moulds.", "Prototyping"],
  ["kiln-firing", "Kiln firing", "Firing services for clay, glaze and glass work.", "Craft"],
  ["textiles", "Textiles", "Fabric sourcing, sampling and textile construction.", "Soft goods"],
  ["sewing", "Sewing", "Patterning, sewing and soft-goods assembly.", "Soft goods"],
  ["soft-goods-prototyping", "Soft-goods prototyping", "Bags, wearables and fabric object prototypes.", "Soft goods"],
  ["photography", "Photography", "Studio and location photography for products and campaigns.", "Media"],
  ["videography", "Videography", "Production crews for launches, documentation and campaigns.", "Media"],
].map(([slug, name, description, group], index) => ({
  id: `svc_${index + 1}`,
  slug,
  name,
  description,
  group,
}));

export const materials: Material[] = [
  "aluminium",
  "plywood",
  "mild steel",
  "stainless steel",
  "acrylic",
  "brass",
  "ceramic",
  "fabric",
  "paper",
  "cardboard",
  "resin",
  "foam",
  "bamboo",
  "glass",
  "electronics",
  "vinyl",
  "leather",
  "recycled plastic",
].map((name, index) => ({
  id: `mat_${index + 1}`,
  name,
  slug: name.replace(/\s+/g, "-"),
}));

const image = (slug: string) => `/demo/${slug}.svg`;

export const businesses: Business[] = [
  {
    id: "biz_ubi_formworks",
    name: "Ubi Formworks Studio",
    slug: "ubi-formworks-studio",
    shortDescription: "Wood, laminate and CNC-routed objects for exhibitions and product prototypes.",
    description:
      "A fictional workshop combining traditional bench craft with CNC routing for designers, artists and retail teams. Strong for quick visual prototypes, plinths and small-run objects.",
    websiteUrl: "https://example.com/ubi-formworks",
    publicEmail: "hello@ubi-formworks.example",
    publicPhone: "+65 6000 0101",
    location: "Ubi",
    showFullAddress: false,
    minimumBudget: 1200,
    typicalLeadTime: 21,
    businessType: "workshop",
    acceptsPrototypes: true,
    acceptsProduction: true,
    offersOnsiteService: true,
    offersRemoteService: false,
    verificationStatus: "verified",
    publicationStatus: "published",
    featured: true,
    claimed: true,
    endorsementCount: 0,
    services: ["woodworking", "carpentry", "cnc-routing", "installation"],
    materials: ["plywood", "acrylic", "bamboo", "recycled plastic"],
    processes: ["CNC routing", "Joinery", "Laminate finishing"],
    projectTypes: ["one-off", "prototype", "small-batch", "installation"],
    heroImage: image("ubi-formworks"),
    demoNotice: "Fictional demo business.",
    portfolio: ["Retail display system", "Museum handling table", "Flat-pack stool edition"].map((title, index) => ({
      id: `ubi_${index}`,
      title,
      description: "Demo portfolio item using generated geometric placeholder imagery.",
      tags: ["plywood", "cnc-routing", "prototype"],
      imageUrl: image(`portfolio-wood-${index + 1}`),
    })),
  },
  {
    id: "biz_kaki_precision",
    name: "Kaki Bukit Precision Works",
    slug: "kaki-bukit-precision-works",
    shortDescription: "Machined aluminium parts, jigs and functional metal prototypes.",
    description:
      "A fictional precision workshop for creators who need aluminium and steel components made with clear tolerances and pragmatic prototyping advice.",
    websiteUrl: "https://example.com/kaki-precision",
    publicEmail: "studio@kakiprecision.example",
    location: "Kaki Bukit",
    showFullAddress: false,
    minimumBudget: 1800,
    typicalLeadTime: 28,
    businessType: "manufacturer",
    acceptsPrototypes: true,
    acceptsProduction: true,
    offersOnsiteService: false,
    offersRemoteService: true,
    verificationStatus: "verified",
    publicationStatus: "published",
    featured: true,
    claimed: true,
    endorsementCount: 0,
    services: ["metal-fabrication", "cnc-machining", "metal-finishing"],
    materials: ["aluminium", "mild steel", "stainless steel", "brass"],
    processes: ["CNC milling", "TIG welding", "Powder coating"],
    projectTypes: ["prototype", "small-batch", "production"],
    heroImage: image("kaki-precision"),
    demoNotice: "Fictional demo business.",
    portfolio: ["Aluminium camera rig", "Retail fixture brackets", "Sensor enclosure"].map((title, index) => ({
      id: `kaki_${index}`,
      title,
      description: "Demo portfolio item using generated geometric placeholder imagery.",
      tags: ["aluminium", "cnc-machining", "prototype"],
      imageUrl: image(`portfolio-metal-${index + 1}`),
    })),
  },
  {
    id: "biz_tai_seng_interactive",
    name: "Tai Seng Interactive Lab",
    slug: "tai-seng-interactive-lab",
    shortDescription: "Creative technology prototypes for installations, launches and learning spaces.",
    description:
      "A fictional creative-technology team building sensor-driven prototypes, lighting behaviours and interactive proof-of-concepts.",
    websiteUrl: "https://example.com/tai-seng-lab",
    publicEmail: "make@taisenglab.example",
    location: "Tai Seng",
    showFullAddress: false,
    minimumBudget: 3500,
    typicalLeadTime: 35,
    businessType: "studio",
    acceptsPrototypes: true,
    acceptsProduction: false,
    offersOnsiteService: true,
    offersRemoteService: true,
    verificationStatus: "claimed",
    publicationStatus: "published",
    featured: true,
    claimed: true,
    endorsementCount: 0,
    services: ["creative-technology", "electronics-prototyping", "installation", "product-design"],
    materials: ["electronics", "acrylic", "aluminium"],
    processes: ["Arduino", "Sensor prototyping", "LED systems"],
    projectTypes: ["prototype", "installation"],
    heroImage: image("tai-seng-interactive"),
    demoNotice: "Fictional demo business.",
    portfolio: ["Responsive light wall", "Museum button interface", "Retail launch counter"].map((title, index) => ({
      id: `taiseng_${index}`,
      title,
      description: "Demo portfolio item using generated geometric placeholder imagery.",
      tags: ["interactive", "electronics-prototyping", "installation"],
      imageUrl: image(`portfolio-tech-${index + 1}`),
    })),
  },
  {
    id: "biz_gelang_print_room",
    name: "Geylang Print Room",
    slug: "geylang-print-room",
    shortDescription: "Short-run print, packaging mockups and tactile paper finishing.",
    description: "A fictional print room for campaign prototypes, packaging samples and specialty paper objects.",
    websiteUrl: "https://example.com/geylang-print",
    publicEmail: "orders@geylangprint.example",
    location: "Geylang",
    showFullAddress: false,
    minimumBudget: 600,
    typicalLeadTime: 12,
    businessType: "supplier",
    acceptsPrototypes: true,
    acceptsProduction: true,
    offersOnsiteService: false,
    offersRemoteService: true,
    verificationStatus: "verified",
    publicationStatus: "published",
    featured: false,
    claimed: true,
    endorsementCount: 0,
    services: ["printing", "die-cutting", "packaging-design", "signage"],
    materials: ["paper", "cardboard", "vinyl"],
    processes: ["Digital print", "Foil mockups", "Creasing"],
    projectTypes: ["prototype", "small-batch", "production"],
    heroImage: image("geylang-print"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
  {
    id: "biz_woodlands_mould",
    name: "Woodlands Mould Collective",
    slug: "woodlands-mould-collective",
    shortDescription: "Silicone moulding, resin casting and model-making support.",
    description: "A fictional collective helping artists and product teams duplicate forms and test finishes.",
    websiteUrl: "https://example.com/woodlands-mould",
    publicEmail: "hello@woodlandsmould.example",
    location: "Woodlands",
    showFullAddress: false,
    minimumBudget: 900,
    typicalLeadTime: 18,
    businessType: "workshop",
    acceptsPrototypes: true,
    acceptsProduction: false,
    offersOnsiteService: false,
    offersRemoteService: true,
    verificationStatus: "unverified",
    publicationStatus: "published",
    featured: false,
    claimed: false,
    endorsementCount: 0,
    services: ["model-making", "mould-making", "3d-printing"],
    materials: ["resin", "foam", "acrylic"],
    processes: ["Silicone moulds", "Resin casting", "Sanding"],
    projectTypes: ["one-off", "prototype"],
    heroImage: image("woodlands-mould"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
  {
    id: "biz_yishun_softgoods",
    name: "Yishun Softgoods Atelier",
    slug: "yishun-softgoods-atelier",
    shortDescription: "Fabric prototypes, sewn samples and bag construction.",
    description: "A fictional soft-goods atelier for designers exploring textile products, wearables and campaign props.",
    websiteUrl: "https://example.com/yishun-softgoods",
    publicEmail: "sample@yishunsoftgoods.example",
    location: "Yishun",
    showFullAddress: false,
    minimumBudget: 700,
    typicalLeadTime: 16,
    businessType: "independent",
    acceptsPrototypes: true,
    acceptsProduction: true,
    offersOnsiteService: false,
    offersRemoteService: true,
    verificationStatus: "claimed",
    publicationStatus: "published",
    featured: false,
    claimed: true,
    endorsementCount: 0,
    services: ["textiles", "sewing", "soft-goods-prototyping"],
    materials: ["fabric", "leather"],
    processes: ["Pattern drafting", "Sewing", "Edge binding"],
    projectTypes: ["prototype", "small-batch"],
    heroImage: image("yishun-softgoods"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
  {
    id: "biz_jurong_large_format",
    name: "Jurong Large Format Works",
    slug: "jurong-large-format-works",
    shortDescription: "Large-format graphics, vinyl, hoarding and event signage.",
    description: "A fictional production shop for launch environments and spatial campaign graphics.",
    websiteUrl: "https://example.com/jurong-format",
    publicEmail: "studio@jurongformat.example",
    location: "Jurong",
    showFullAddress: false,
    minimumBudget: 1000,
    typicalLeadTime: 10,
    businessType: "supplier",
    acceptsPrototypes: false,
    acceptsProduction: true,
    offersOnsiteService: true,
    offersRemoteService: true,
    verificationStatus: "verified",
    publicationStatus: "published",
    featured: false,
    claimed: true,
    endorsementCount: 0,
    services: ["printing", "signage", "event-fabrication"],
    materials: ["vinyl", "paper", "acrylic"],
    processes: ["UV print", "Vinyl application", "Mounting"],
    projectTypes: ["production", "installation"],
    heroImage: image("jurong-format"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
  {
    id: "biz_bukit_merah_photo",
    name: "Bukit Merah Object Studio",
    slug: "bukit-merah-object-studio",
    shortDescription: "Product photography and campaign documentation for made objects.",
    description: "A fictional photo studio with a careful eye for craft, texture and process documentation.",
    websiteUrl: "https://example.com/object-studio",
    publicEmail: "shoot@objectstudio.example",
    location: "Bukit Merah",
    showFullAddress: false,
    minimumBudget: 900,
    typicalLeadTime: 14,
    businessType: "studio",
    acceptsPrototypes: true,
    acceptsProduction: true,
    offersOnsiteService: true,
    offersRemoteService: false,
    verificationStatus: "claimed",
    publicationStatus: "published",
    featured: false,
    claimed: true,
    endorsementCount: 0,
    services: ["photography", "videography"],
    materials: ["paper", "ceramic", "aluminium", "fabric"],
    processes: ["Still-life sets", "Short video", "Retouching"],
    projectTypes: ["one-off", "production"],
    heroImage: image("bukit-merah-photo"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
  {
    id: "biz_kampong_glam_design",
    name: "Kampong Glam Product Office",
    slug: "kampong-glam-product-office",
    shortDescription: "Product design, prototype planning and fabrication coordination.",
    description: "A fictional design office helping founders and artists translate ideas into manufacturable briefs.",
    websiteUrl: "https://example.com/product-office",
    publicEmail: "brief@productoffice.example",
    location: "Kampong Glam",
    showFullAddress: false,
    minimumBudget: 2500,
    typicalLeadTime: 24,
    businessType: "consultancy",
    acceptsPrototypes: true,
    acceptsProduction: false,
    offersOnsiteService: true,
    offersRemoteService: true,
    verificationStatus: "verified",
    publicationStatus: "published",
    featured: false,
    claimed: true,
    endorsementCount: 0,
    services: ["product-design", "3d-printing", "model-making"],
    materials: ["aluminium", "plywood", "resin", "recycled plastic"],
    processes: ["CAD", "Design for manufacture", "Supplier briefing"],
    projectTypes: ["prototype", "small-batch"],
    heroImage: image("kampong-glam-design"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
  {
    id: "biz_queenstown_ceramic",
    name: "Queenstown Ceramic Testbed",
    slug: "queenstown-ceramic-testbed",
    shortDescription: "Ceramic object sampling, glaze tests and kiln firing.",
    description: "A fictional ceramics testbed for artists, designers and small hospitality object projects.",
    websiteUrl: "https://example.com/ceramic-testbed",
    publicEmail: "clay@ceramictestbed.example",
    location: "Queenstown",
    showFullAddress: false,
    minimumBudget: 500,
    typicalLeadTime: 20,
    businessType: "independent",
    acceptsPrototypes: true,
    acceptsProduction: true,
    offersOnsiteService: false,
    offersRemoteService: false,
    verificationStatus: "unverified",
    publicationStatus: "published",
    featured: false,
    claimed: false,
    endorsementCount: 0,
    services: ["ceramics", "mould-making", "kiln-firing"],
    materials: ["ceramic"],
    processes: ["Slip casting", "Glaze testing", "Kiln firing"],
    projectTypes: ["one-off", "prototype", "small-batch"],
    heroImage: image("queenstown-ceramic"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
  {
    id: "biz_tai_seng_exhibit",
    name: "Tai Seng Exhibit Builders",
    slug: "tai-seng-exhibit-builders",
    shortDescription: "Exhibition structures, plinths, walling and installation crews.",
    description: "A fictional fabrication crew for galleries, brand activations and temporary built environments.",
    websiteUrl: "https://example.com/exhibit-builders",
    publicEmail: "build@exhibitbuilders.example",
    location: "Tai Seng",
    showFullAddress: false,
    minimumBudget: 5000,
    typicalLeadTime: 30,
    businessType: "workshop",
    acceptsPrototypes: false,
    acceptsProduction: true,
    offersOnsiteService: true,
    offersRemoteService: false,
    verificationStatus: "verified",
    publicationStatus: "published",
    featured: false,
    claimed: true,
    endorsementCount: 0,
    services: ["event-fabrication", "installation", "signage", "carpentry"],
    materials: ["plywood", "mild steel", "acrylic", "vinyl"],
    processes: ["Site install", "Spray finish", "Build drawings"],
    projectTypes: ["installation", "production"],
    heroImage: image("tai-seng-exhibit"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
  {
    id: "biz_ubi_additive",
    name: "Ubi Additive Bench",
    slug: "ubi-additive-bench",
    shortDescription: "3D-printed prototypes, fixtures and low-volume plastic parts.",
    description: "A fictional additive bench supporting fast iteration for designers and hardware teams.",
    websiteUrl: "https://example.com/additive-bench",
    publicEmail: "print@additivebench.example",
    location: "Ubi",
    showFullAddress: false,
    minimumBudget: 350,
    typicalLeadTime: 7,
    businessType: "independent",
    acceptsPrototypes: true,
    acceptsProduction: true,
    offersOnsiteService: false,
    offersRemoteService: true,
    verificationStatus: "claimed",
    publicationStatus: "published",
    featured: false,
    claimed: true,
    endorsementCount: 0,
    services: ["3d-printing", "model-making", "product-design"],
    materials: ["resin", "recycled plastic", "electronics"],
    processes: ["SLA printing", "FDM printing", "Assembly checks"],
    projectTypes: ["prototype", "small-batch"],
    heroImage: image("ubi-additive"),
    demoNotice: "Fictional demo business.",
    portfolio: [],
  },
];

export const projects: Project[] = [
  {
    id: "project_aluminium_lamp",
    ownerId: "demo_creative",
    title: "Aluminium table lamp prototype",
    description: "A one-off aluminium lamp with machined hinge details and a warm dimmable LED.",
    intendedOutcome: "Working prototype for photography and investor conversations.",
    projectType: "physical",
    quantity: "1",
    dimensions: "300 x 180 x 420mm",
    materials: ["aluminium", "electronics"],
    knownServices: ["cnc-machining", "electronics-prototyping"],
    prototypeOrProduction: "prototype",
    preferredLocation: "Ubi",
    budgetMin: 2500,
    budgetMax: 7000,
    deadline: "2026-09-15",
    deadlineFlexibility: "Flexible by two weeks",
    status: "draft",
  },
  {
    id: "project_exhibition_wall",
    ownerId: "demo_creative",
    title: "Interactive exhibition wall",
    description: "A travelling exhibition wall with touch sensors, lighting and replaceable graphic panels.",
    intendedOutcome: "Installed experience for a public showcase.",
    projectType: "both",
    materials: ["plywood", "electronics", "vinyl"],
    knownServices: ["creative-technology", "event-fabrication"],
    prototypeOrProduction: "both",
    preferredLocation: "Tai Seng",
    budgetMin: 12000,
    budgetMax: 30000,
    status: "seeking_providers",
  },
  {
    id: "project_ceramic_packaging",
    ownerId: "demo_creative",
    title: "Ceramic gift set and paper sleeve",
    description: "Small ceramic cups with a textured paper sleeve and short-run packaging.",
    intendedOutcome: "Pilot batch for a hospitality client.",
    projectType: "physical",
    materials: ["ceramic", "paper"],
    knownServices: ["ceramics", "packaging-design", "printing"],
    prototypeOrProduction: "production",
    preferredLocation: "Queenstown",
    budgetMin: 3000,
    budgetMax: 9000,
    status: "draft",
  },
  {
    id: "project_softgoods",
    ownerId: "demo_creative",
    title: "Recycled fabric event tote",
    description: "Soft-goods prototype for a durable event tote using recycled fabric.",
    intendedOutcome: "Sample and costing for 300 units.",
    projectType: "physical",
    materials: ["fabric"],
    knownServices: ["sewing", "soft-goods-prototyping"],
    prototypeOrProduction: "both",
    preferredLocation: "Yishun",
    budgetMin: 1500,
    budgetMax: 6000,
    status: "draft",
  },
];

export const businessRecommendations: BusinessRecommendation[] = [
  {
    id: "rec_ubi_1",
    businessId: "biz_ubi_formworks",
    recommenderName: "Alicia Tan",
    recommenderRole: "Exhibition designer",
    relationship: "client",
    projectContext: "Museum handling table and plinth prototypes",
    recommendedFor: ["Clear fabrication advice", "Careful CNC routing", "Reliable installation support"],
    comment:
      "They helped us refine a loose drawing into something buildable, flagged material issues early, and kept the install calm.",
    mediaUrls: [image("portfolio-wood-1")],
    permissionToContact: true,
    permissionToPublishName: true,
    status: "approved",
    createdAt: "2026-05-18",
  },
  {
    id: "rec_kaki_1",
    businessId: "biz_kaki_precision",
    recommenderName: "Marcus Lee",
    recommenderRole: "Product founder",
    relationship: "client",
    projectContext: "Machined aluminium enclosure prototype",
    recommendedFor: ["Practical tolerance advice", "Good prototype communication"],
    comment:
      "The team translated our CAD into a workable prototype and explained the machining trade-offs without making the process feel opaque.",
    mediaUrls: [image("portfolio-metal-1")],
    permissionToContact: true,
    permissionToPublishName: true,
    status: "approved",
    createdAt: "2026-04-29",
  },
  {
    id: "rec_tai_seng_1",
    businessId: "biz_tai_seng_interactive",
    recommenderName: "Nadia Rahim",
    relationship: "collaborator",
    projectContext: "Interactive lighting proof of concept",
    recommendedFor: ["Thoughtful prototyping", "Fast sensor tests"],
    comment:
      "They were generous with technical options and helped the creative team understand what could be proven quickly before committing to a full build.",
    mediaUrls: [image("portfolio-tech-1")],
    permissionToContact: false,
    permissionToPublishName: false,
    status: "approved",
    createdAt: "2026-03-11",
  },
  {
    id: "rec_pending_1",
    businessId: "biz_gelang_print_room",
    recommenderName: "Demo recommender",
    relationship: "client",
    projectContext: "Packaging mockup sprint",
    recommendedFor: ["Responsive quoting"],
    comment:
      "Pending demo recommendation for admin moderation. This would not appear publicly until approved.",
    mediaUrls: [],
    permissionToContact: true,
    permissionToPublishName: false,
    status: "pending",
    createdAt: "2026-07-01",
  },
];

export function getApprovedRecommendationsForBusiness(businessId: string) {
  return businessRecommendations.filter(
    (recommendation) => recommendation.businessId === businessId && recommendation.status === "approved",
  );
}
